### ISSUE TITLE
Brystkreft eksempel tar i bruk treningsdata som testdata?

### ISSUE THREAD

**Issue by AudunBorgersen** [cair/pyTsetlinMachine#10]
Hei, ser ut som om BreastCancerDemo.py i linje 21 tar i bruk tidligere treningsdata som testdata. Burde ikke den linjen holdes utenfor for loopen?

**Comment by olegranmo** [comment]
Hei Audun - takk for melding! Akkurat den demoen er forskjellige fra de andre. Den starter treningen helt fra scratch i hver runde og gjennomsnittet fra uavhengige kjøringer regnes ut til slutt. For å få et er robust estimat for accuracy deles dataene på nytt for hver kjøring. De andre demoene har incremental satt til True for fit(), og da slettes ikke tilstanden i TMen.
